// src/features/sessions/SessionSidebar.vue
<script setup lang="ts">
import { computed } from "vue";
import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { formatSolveTime } from "../timer/timerFormat";
import SolveList from "./SolveList.vue";
import { sessionStats } from "./solveStats";
import type { Session, Solve, StatKey } from "./types";

const newSessionValue = "__new_session__";
const statKeys: StatKey[] = ["single", "ao5", "ao12", "ao50", "ao100"];

const props = withDefaults(
  defineProps<{
    sessions: Session[];
    activeSessionId: string;
    disabled?: boolean;
    className?: string;
  }>(),
  {
    disabled: false,
    className: "",
  },
);

const emit = defineEmits<{
  sessionChange: [sessionId: string];
  newSession: [];
  clear: [];
  export: [];
  openSolve: [solve: Solve];
  penalty: [solveId: string, penalty: Solve["penalty"]];
  delete: [solveId: string];
}>();

const activeSession = computed(
  () => props.sessions.find((session) => session.id === props.activeSessionId) ?? props.sessions[0],
);
const stats = computed(() => sessionStats(activeSession.value.solves));

function changeSession(value: unknown) {
  if (typeof value !== "string") {
    return;
  }

  if (value === newSessionValue) {
    emit("newSession");
    return;
  }

  emit("sessionChange", value);
}

function statValue(value: number | null): string {
  if (value == null) {
    return "-";
  }

  return Number.isFinite(value) ? formatSolveTime(value) : "DNF";
}
</script>

<template>
  <aside :class="['flex min-h-0 flex-col border-white/[0.07] bg-[#0a0a0b]', className]">
    <div class="border-b border-white/[0.07] px-5 py-4 md:px-6">
      <div class="mb-1 text-[10px] font-semibold uppercase tracking-[0.16em] text-zinc-700">
        Session
      </div>
      <Select
        :model-value="activeSessionId"
        :disabled="disabled"
        @update:model-value="changeSession"
      >
        <SelectTrigger
          data-global-shortcuts="ignore"
          class="session-select-trigger h-11 w-full border-white/15 bg-zinc-900/80 text-sm font-semibold text-zinc-100 shadow-[inset_0_1px_0_rgb(255_255_255_/_4%),0_0_0_1px_rgb(0_0_0_/_35%)] hover:border-white/25 hover:bg-zinc-800/70"
        >
          <SelectValue />
        </SelectTrigger>
        <SelectContent>
          <SelectItem v-for="session in sessions" :key="session.id" :value="session.id">
            {{ session.name }}
          </SelectItem>
          <SelectItem :value="newSessionValue">+ New session...</SelectItem>
        </SelectContent>
      </Select>
      <div class="mt-2 flex gap-4 font-mono text-[11px] text-zinc-600">
        <span
          ><b class="text-zinc-300">{{ stats.count }}</b> solves</span
        >
        <span>
          mean
          <b class="text-zinc-300">{{ stats.mean == null ? "-" : formatSolveTime(stats.mean) }}</b>
        </span>
      </div>
    </div>
    <div
      class="grid grid-cols-[1fr_auto_auto] gap-x-3 gap-y-1 border-b border-white/[0.07] px-5 py-4 font-mono text-xs md:px-6"
    >
      <span class="text-[10px] uppercase tracking-[0.16em] text-zinc-700">Avg</span>
      <span class="text-right text-[10px] uppercase tracking-[0.16em] text-zinc-700">Now</span>
      <span class="text-right text-[10px] uppercase tracking-[0.16em] text-zinc-700">Best</span>
      <template v-for="key in statKeys" :key="key">
        <span class="text-zinc-500">{{ key }}</span>
        <span class="text-right text-zinc-100">{{ statValue(stats.current[key]) }}</span>
        <span class="text-right text-indigo-300">
          {{ stats.best[key] == null ? "-" : formatSolveTime(stats.best[key] as number) }}
        </span>
      </template>
    </div>
    <div
      class="grid grid-cols-[2.25rem_1fr_3.5rem_3.5rem] px-5 pb-1 pt-3 text-[10px] font-semibold uppercase tracking-[0.14em] text-zinc-700 md:px-6"
    >
      <span>#</span>
      <span>Time</span>
      <span class="text-right">ao5</span>
      <span class="text-right">ao12</span>
    </div>
    <SolveList
      :solves="activeSession.solves"
      @open="emit('openSolve', $event)"
      @penalty="(solveId, penalty) => emit('penalty', solveId, penalty)"
      @delete="emit('delete', $event)"
    />
    <div class="flex gap-2 border-t border-white/[0.07] px-5 py-3 md:px-6">
      <Button
        type="button"
        :disabled="disabled"
        variant="outline"
        class="sidebar-button h-auto"
        @click="emit('newSession')"
      >
        New
      </Button>
      <Button type="button" variant="outline" class="sidebar-button h-auto" @click="emit('export')">
        Export
      </Button>
      <Button
        type="button"
        :disabled="disabled"
        variant="outline"
        class="sidebar-button text-red-300"
        @click="emit('clear')"
      >
        Clear
      </Button>
    </div>
  </aside>
</template>

// src/features/sessions/SessionSidebar.tsx
import { Fragment } from "react";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "../../shared/components/Select";
import { formatSolveTime } from "../timer/timerFormat";
import { SolveList } from "./SolveList";
import { sessionStats } from "./solveStats";
import type { Session, Solve, StatKey } from "./types";

type SessionSidebarProps = {
  sessions: Session[];
  activeSessionId: string;
  mobileOpen?: boolean;
  disabled?: boolean;
  onSessionChange: (sessionId: string) => void;
  onNewSession: () => void;
  onClear: () => void;
  onExport: () => void;
  onOpenSolve: (solve: Solve) => void;
  onPenalty: (solveId: string, penalty: Solve["penalty"]) => void;
  onDelete: (solveId: string) => void;
};

const STAT_KEYS: StatKey[] = ["single", "ao5", "ao12", "ao50", "ao100"];
const NEW_SESSION_VALUE = "__new_session__";

export function SessionSidebar({
  sessions,
  activeSessionId,
  mobileOpen = false,
  disabled = false,
  onSessionChange,
  onNewSession,
  onClear,
  onExport,
  onOpenSolve,
  onPenalty,
  onDelete,
}: SessionSidebarProps) {
  const activeSession = sessions.find((session) => session.id === activeSessionId) ?? sessions[0];
  const stats = sessionStats(activeSession.solves);

  return (
    <aside
      className={`z-30 flex min-h-0 flex-col border-white/[0.07] bg-[#0a0a0b] md:static md:translate-x-0 md:border-r ${
        mobileOpen
          ? "fixed inset-y-0 left-0 w-[min(360px,92vw)] translate-x-0 border-r shadow-2xl shadow-black/60"
          : "fixed inset-y-0 left-0 w-[min(360px,92vw)] -translate-x-full border-r transition md:w-auto"
      }`}
    >
      <div className="border-b border-white/[0.07] px-5 py-4 md:px-6">
        <div className="mb-1 text-[10px] font-semibold uppercase tracking-[0.16em] text-zinc-700">
          Session
        </div>
        <Select
          value={activeSessionId}
          disabled={disabled}
          onValueChange={(value) => {
            if (value === NEW_SESSION_VALUE) {
              onNewSession();
              return;
            }

            onSessionChange(value);
          }}
        >
          <SelectTrigger className="session-select-trigger w-full border-white/15 bg-zinc-900/80 text-sm font-semibold shadow-[inset_0_1px_0_rgb(255_255_255_/_4%),0_0_0_1px_rgb(0_0_0_/_35%)] hover:border-white/25 hover:bg-zinc-800/70">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {sessions.map((session) => (
              <SelectItem key={session.id} value={session.id}>
                {session.name}
              </SelectItem>
            ))}
            <SelectItem value={NEW_SESSION_VALUE}>+ New session...</SelectItem>
          </SelectContent>
        </Select>
        <div className="mt-2 flex gap-4 font-mono text-[11px] text-zinc-600">
          <span>
            <b className="text-zinc-300">{stats.count}</b> solves
          </span>
          <span>
            mean{" "}
            <b className="text-zinc-300">
              {stats.mean == null ? "-" : formatSolveTime(stats.mean)}
            </b>
          </span>
        </div>
      </div>
      <div className="grid grid-cols-[1fr_auto_auto] gap-x-3 gap-y-1 border-b border-white/[0.07] px-5 py-4 font-mono text-xs md:px-6">
        <span className="text-[10px] uppercase tracking-[0.16em] text-zinc-700">Avg</span>
        <span className="text-right text-[10px] uppercase tracking-[0.16em] text-zinc-700">
          Now
        </span>
        <span className="text-right text-[10px] uppercase tracking-[0.16em] text-zinc-700">
          Best
        </span>
        {STAT_KEYS.map((key) => (
          <Fragment key={key}>
            <span key={`${key}-k`} className="text-zinc-500">
              {key}
            </span>
            <span key={`${key}-c`} className="text-right text-zinc-100">
              {stats.current[key] == null
                ? "-"
                : Number.isFinite(stats.current[key])
                  ? formatSolveTime(stats.current[key])
                  : "DNF"}
            </span>
            <span key={`${key}-b`} className="text-right text-indigo-300">
              {stats.best[key] == null ? "-" : formatSolveTime(stats.best[key])}
            </span>
          </Fragment>
        ))}
      </div>
      <div className="grid grid-cols-[2.25rem_1fr_3.5rem_3.5rem] px-5 pb-1 pt-3 text-[10px] font-semibold uppercase tracking-[0.14em] text-zinc-700 md:px-6">
        <span>#</span>
        <span>Time</span>
        <span className="text-right">ao5</span>
        <span className="text-right">ao12</span>
      </div>
      <SolveList
        solves={activeSession.solves}
        onOpen={onOpenSolve}
        onPenalty={onPenalty}
        onDelete={onDelete}
      />
      <div className="flex gap-2 border-t border-white/[0.07] px-5 py-3 md:px-6">
        <button type="button" disabled={disabled} onClick={onNewSession} className="sidebar-button">
          New
        </button>
        <button type="button" onClick={onExport} className="sidebar-button">
          Export
        </button>
        <button
          type="button"
          disabled={disabled}
          onClick={onClear}
          className="sidebar-button text-red-300"
        >
          Clear
        </button>
      </div>
    </aside>
  );
}
